/**
 * supabase-secrets.js — AUTO-GENERATED (do not edit)
 * Generated by: npm run sync:supabase
 * Source: pixel-dashboard/.env.local
 */

export const SUPABASE_URL = 'https://ehoifdtqcsihxqnveiyf.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVob2lmZHRxY3NpaHhxbnZlaXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzNzk2OTQsImV4cCI6MjA5NDk1NTY5NH0.uJ8ZgH2_fWXyC-faAJGeqeJiUgoqkwK2oJfQYIj7swI';
